title: security-strategy-essentials
tagline: A brand new course on Learning Lab
description: 'Course repo for Learning Lab course "Security strategy essentials"'
template:
  repo: security-strategy-essentials-template
  name: security-strategy-essentials
before:
  - type: updateBranchProtection
  - type: createPullRequest
    title: Update the vulnerable dependency
    body: 03_update-dependency.md
    head: update-dependency
  - type: octokit
    method: 'repos.get'
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    action_id: gotten_repo
  - type: createIssue
    title: Welcome
    body: 01a_class-introduction-issue.md
    data:
      private: '%actions.gotten_repo.data.private%'

steps:

  # Step 1
  # Learner enables GH pages for game
  # Bot creates issue to report a vulnerability

  - title: Enable repository settings
    description: Enable settings in your repository for the next activities.
    event: page_build
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: createIssue
        title: Find repository vulnerabilities
        body: 02_find-vulnerabilities.md
        action_id: firstIssue
      - type: closeIssue
        issue: Welcome
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: respond
        issue: Welcome
        with: 02_closed-issue.md
        data:
          url: '%actions.firstIssue.data.html_url%'
          pages: '%actions.pagesUrl.data.html_url%'

  # Step 2
  # Learner comments on issue with the recommended updated version
  # Bot closes issue and responds with making change in PR

  - title: Find the vulnerable dependency
    description: Find the vulnerable dependency, and comment with the suggested update version.
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: respond
        with: 03_found-vulnerability.md
      - type: closeIssue
        issue: Find repository vulnerabilities

  # Step 3
  # Learner updates the dependency
  # Bot responds

  - title: Update the dependency version
    description: Edit the file in the pull request to update the dependency.
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: getFileContents
        action_id: fileContents
        filename: package.json
      - type: gate
        left: '/"debug": "[\^\~\>]?\=?\d+\.\d+\.\d+"/g'
        operator: test
        right: '%actions.fileContents%'
        else:
        - type: respond
          issue: 3
          with: 03_adding-bad-changes.md
      - type: removeBranchProtection
      - type: respond
        with: 03_good-pr.md

  # Step 4
  # Learner merges in the PR
  # Bot creates new issue talking about automating process with dependabot
  # Bot responds with link to new issue

  - title: Merge your pull request
    description: Merge the pull request you've opened to update the vulnerability dependency.
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
        else:
        - type: octokit
          method: issues.edit
          state: open
          owner: '%payload.repository.owner.login%'
          repo: '%payload.repository.name%'
          number: '%payload.repository.pull_request.number%'
        - type: respond
          with: 03_accidental-close.md
      - type: updateBranchProtection
      - type: createIssue
        title: Add dependabot to your repository
        body: 02_trigger-wip.md #dependabot issue body response
        action_id: dependabot_issue
      - type: respond
        with: 04a_good-merge.md #Link to dependabot issue

  # Step 5
  # Learner installs dependabot on repository and closes the issue when done
  # Bot creates new issue about adding a security policy. (Perhaps just a response and not a new issue)

  - title: Enable dependabot
    description: Install dependabot on your repository.
    event: issues.closed
    link: '{{ repoUrl }}/issues/5'
    actions:
    - type: createIssue
      title: Add a Security Policy
      body: 02_trigger-wip.md #security policy issue body (add branch name instructions and examples)
      action_id: securityIssue
    - type: respond
      with: 01_successful-close.md #link to security issue
      data:
        url: '%actions.securityIssue.data.html_url%'

  # Step 6
  # Learner adds a security polcy through the security tab thereby creating a new PR
  # Bot responds in PR with suggested information about the security policy. Prompts learner to merge when ready
  # Learner merges the PR
  # Bot responds with link to new PR acting as a contributor making a change to the repository with accidental sensitive data committed to PR

  - title: Add a SECURITY.md file
    description: Add a SECURITY.md file to your repository.
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/4'
    actions:
      - type: gate
          left: '%payload.pull_request.merged%'
        else:
        - type: respond
          with: REPLACE-ME.md #error response that PR was closed not merged. Reopen PR
      - type: createPullRequest
        title: Add wolverine octocat to game
        body: replace-me.md # body of the contributor PR
        head: add-wolverine
        action_id: addWolverine
      - type: respond
        with: replace.md # Bot response to new PR
        data:
          url: '%actions.addWolverine.data.html_url%'


  # Step 7
  # Learner removes sensitive data in PR
  # Bot responds with information on sensitive data and contacting support for garbage collection and caching

  - title: Remove sensitive data in a pull request
    description: Remove sensitive data pushed to a pull request
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/3'
    actions:
    - type: octokit
      method: pullRequests.listFiles
      owner: '%payload.repository.owner.login%'
      repo: '%payload.repository.name%'
      number: '%payload.pull_request.number%'
      action_id: pr_files
    - type: gate
      left: '%actions.pr_files.data%'
      operator: includes
      right: 'filename:.env'
      else:
      - type: respond
        with: 03_make-file-changes.md #failed response to remove .env file
    - type: respond
      with: 03_discovering-api-endpoints.md #success response to remove .env file | Add note about contacting support for garbage collection

  # Step 8
  # Learner approves PR
  # Bot merges PR and responds with link to new PR to create a .gitignore file

  - title: Approve the pull request
    description: Approve the contributors pull request
    event: pull_request_review.submitted
    link: '{{ repoUrl }}/pull/4'
    actions:
      - type: gate
        left: '%payload.review.state%'
        operator: ===
        right: approved
        else:
        - type: respond
          with: 05_fail-ignore.md # add response to add an approving review
      - type: mergePullRequest
      - type: createPullRequest
        title: Add .gitignore file
        body: replace-me.md # body of the .gitignore body
        head: add-gitignore
        action_id: addGitignore
      - type: respond
        with: replace.md # Bot response to new PR
        data:
          url: '%actions.addGitignore.data.html_url%'

  # Step 9
  # Learner adds .env to the .gitignore file
  # Bot validates file update

  - title: Add a `.gitignore` file
    description: The `.gitignore` file is ready to be edited in an open pull request. Add the `.env` file to the `.gitignore` file.
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/4'
    actions:
      - type: getFileContents
        action_id: fileContents
        filename: .gitignore
      - type: gate
        left: '/\.env/m'
        operator: test
        right: '%actions.fileContents%'
        else:
        - type: respond
          with: 05_fail-ignore.md
      - type: removeBranchProtection
      - type: respond
        with: 05_good-ignore.md

  # Step 10
  # Learner merges PR
  # Bot creates new issue about sensitive date in the repository's history
  # Bot prompts learner to provide first commit SHA ID that needs to be removed

  - title: Merge the pull request
    description: Merge the second pull request with updates to the `.gitignore` file.
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/4'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
        else:
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          - type: respond
            with: 05_early-close.md
      - type: createIssue
        title: Sensitive data committed to history
        body: 06b_committed-sensitive-data.md # sensitive data in history isse body | instruct learner to force push change in a PR and bot will respond there
        action_id: committedData
      - type: respond
        with: 06a_nice-merge.md # response to next issue on resolving committed data
        data:
          url: '%actions.committedData.data.html_url%'

  # Step 11
  # Learner comments in issue the commit SHA ID that added the sensitive file
  # Bot validates comment

  - title: Find historical reference to a previous .env file
    description: Find historical reference to a previously committed .env file
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/5'
    actions:
      - type: gate
        left: '848cd8c2043f6161a4f0043bffee212777281494'
        operator: test
        right: '%payload.comment.body%'
        required: false
        else:
          - type: respond
            with: nice-try-message with next steps.md
      - type: respond
        with: nice-job-message with next steps.md
        action_id: historicalCommit

  # Step 12
  # Learner force pushes change to remove historical references of committed file data (commit to add and commit to remove)
  # Bot validates removal of historical reference (56d6fbbd3bcb476b2829c0dff411e3e0b9b03b69 and 848cd8c2043f6161a4f0043bffee212777281494)
  # Bot responds with congratulations issue

  - title: Remove historical reference to a previous .env file
    description: Remove historical reference to a previously committed .env file
    event: push
    link: '{{ repoUrl }}'
    actions:
      - type: getFileContents
        filename: .env
        sha: 848cd8c2043f6161a4f0043bffee212777281494
      - type: gate
        left: 'NODE_ENV=development
               PORT=8626
               # Set your database/API connection information here
               API_KEY=SENSITIVE-VALUE-DATA
               API_URL=SENSITIVE-VALUE-DATA'
        operator: test
        right: '%actions.fileContents%'
        else:
          - type: respond
            with: try-again-response.md
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: createIssue
        title: Congratulations!
        body: 06b_final-issue.md # Final issue
        data:
          url: '%actions.pagesUrl.data.html_url%'
        action_id: finalIssue
      - type: updateBranchProtection
      - type: respond
        with: nice-job.md # replace with nice job removing .env file response
        data:
          url: '%actions.finalIssue.data.html_url%'
