title: security-strategy-essentials
tagline: A brand new course on Learning Lab
description: 'Course repo for Learning Lab course "Security strategy essentials" '
template:
  repo: security-strategy-essentials-template
  name: security-strategy-essentials
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
